# YAML configuration file for YOLOv8 training

# Path to your training and validation datasets
train: /content/drive/MyDrive/data/train  # Path to training images
val: /content/drive/MyDrive/data/val    # Path to validation images

# Number of classes (only 'person' class in this case)
nc: 1

# List of class names
names:
  0: 'person'
